name: ecom_spring_cloud
services:
  nacos:
    image: nacos/nacos-server:v2.2.0
    container_name: ecom_nacos
    ports:
      - 8848:8848
      - 9848:9848
      - 9849:9849
    environment:
      - MODE=standalone
    volumes:
      - nacos-data:/home/nacos
    deploy:
      resources:
        limits:
          memory: 2G

volumes:
  nacos-data: {}