spring:
  cloud:
    gateway:
      routes:
        - id: coupon_route
          uri: lb://ecom-coupon
          predicates:
            - Path=/coupon/**
        - id: member_route
          uri: lb://ecom-member
          predicates:
            - Path=/member/**