spring:
  cloud:
    gateway:
      routes:
        - id: coupon_route
          uri: lb://ecom-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://ecom-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/$\{segment}

        - id: product_route
          uri: lb://ecom-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: ware_route
          uri: lb://ecom-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: search_route
          uri: lb://ecom-search
          predicates:
            - Path=/api/search/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: third_party_route
          uri: lb://ecom-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: renren-route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/renren-fast/$\{segment}

        - id: gulimall-host-route
          uri: lb://ecom-product
          predicates:
            - Host=gulimall.com,www.gulimall.com

        - id: gulimall-search-route
          uri: lb://ecom-search
          predicates:
            - Host=search.gulimall.com